//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string Article { get; set; }
        public string Name { get; set; }
        public int Units_Id { get; set; }
        public decimal Price { get; set; }
        public int Supplier_Id { get; set; }
        public int Manufacturer_Id { get; set; }
        public int Product_Categories_Id { get; set; }
        public int Current_Discount { get; set; }
        public int Coast { get; set; }
        public string Description { get; set; }
        public string PhotoPath { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Units Units { get; set; }
    }
}
